### ISSUE TITLE
error making: ros-noetic-rosgraph-msgs

### ISSUE THREAD

**Issue by guntursiboro** [ros-noetic-arch/ros-noetic-gazebo-ros#5]
I am trying to install ros-noetic-desktop-full 1.5.0-1, but terminated because of 
`error making: ros-noetic-rosgraph-msgs`

So I spesifically install this package to find out more, I use this command in terminal 
`yay -S ros-noetic-rosgraph-msgs --rebuildtree &| tee ros-noetic-rosgraph-msgs.txt`

and here is the output that I get. 
[https://gist.github.com/guntursiboro/c8c706744261d8bac861cacdd6c1663c](url)

Thanks in advanced for you help.

**Comment by acxz** [comment]
@guntursiboro I apologize for taking such a long time to respond. I've been away from this project for a while.

It seems that the link you posted does not work.

I myself just confirmed that I can install ros-noetic-rosgraph-msgs. Please try again and if you still see issues please open this issue again with an error log.

I'm closing this issue for now.
